name: Fly Deploy (backend)

on:
  push:
    branches:
      - feat/backend

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        id: fly_deploy
        working-directory: ./backend
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Send Discord Notification
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          BRANCH_NAME: ${{ github.ref_name }}
          GITHUB_WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          STATUS: ${{ job.status }}
          DEPLOY_URL: https://api-phonoria.fly.dev/
        run: |
          curl -H "Content-Type: application/json" -X POST $DISCORD_WEBHOOK -d '{
            "username": "GitHub Actions",
            "embeds": [{
              "title": "Fly.io Deployment - '${{ env.STATUS }}'",
              "color": "'$(if [ "${{ env.STATUS }}" == "success" ]; then echo 3066993; else echo 15158332; fi)'",
              "fields": [
                { "name": "Branch", "value": "'"${BRANCH_NAME}"'", "inline": true },
                { "name": "Commit", "value": "'"${COMMIT_SHA::7}"'", "inline": true },
                { "name": "Author", "value": "'"${COMMIT_AUTHOR}"'", "inline": true },
                { "name": "Message", "value": "'"${COMMIT_MSG}"'" },
                { "name": "Workflow", "value": "[View Run]('"${GITHUB_WORKFLOW_URL}"')" },
                { "name": "URL", "value": "'"${DEPLOY_URL}"'" }
              ],
              "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
            }]
          }'
